#spring.application.name=Quiz_Application
### Application name
##
### MySQL Database Configuration
##spring.datasource.url=jdbc:mysql://localhost:3306/quizdb
##spring.datasource.username=root
##spring.datasource.password=Shweta@12
##spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
##
### Disable JPA/Hibernate completely
##spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
##spring.jpa.hibernate.ddl-auto=none
##
### Optional: Do not initialize SQL automatically
##spring.sql.init.mode=never
#
#
## MySQL Database Configuration
#spring.datasource.url=jdbc:mysql://localhost:3306/quizdb?useSSL=false&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=Shweta@12
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
## Disable JPA/Hibernate (we use JdbcTemplate)
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
#spring.sql.init.mode=never
#
## Swagger UI
#springdoc.api-docs.path=/v3/api-docs
#springdoc.swagger-ui.path=/swagger-ui.html
#
#


spring.application.name=Quiz_Application
spring.datasource.url=jdbc:mysql://localhost:3306/quizdb?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Shweta@12
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver



